In [31]:
import torch
import numpy as np
from skimage.metrics import peak_signal_noise_ratio as psnr

from careamics.utils.metrics import _zero_mean, scale_invariant_psnr, torch_cast_to_float, _fix, _fix_range

In [45]:
x, y = np.array([1, 2, 3, 4, 5, 6]), np.array([1, 2, 3, 4, 5, 6])
# x, y = torch.tensor([1, 2, 3, 4, 5, 6]), torch.tensor([1, 2, 3, 4, 5, 6])
# x, y = torch_cast_to_float(x), torch_cast_to_float(y)

# scale_invariant_psnr(x, y)
psnr(np.asarray(x), np.asarray(y), data_range=5.)

inf

In [51]:
range_ = (x.max() - x.min()) / x.std()
print(range_)
x_ = _zero_mean(x) / x.std()
print(x_)
# fix
y_ = _zero_mean(y)
print(y_)
x__ = _zero_mean(x_)
print(x__)
# fix range
a = (x__ * y_).sum() / (y_**2).sum()
print(a)
y__ = y_ * a
print(y__)
print(psnr(np.asarray(x__), np.asarray(y__), data_range=range_))
# psnr(
#     np.asarray([-1.3363, -0.8018, -0.2673,  0.2673,  0.8018,  1.3363]),
#     np.asarray([-1.3363, -0.8018, -0.2673,  0.2673,  0.8018,  1.3363]),
#     data_range=2.6726
# )
print(psnr(
    np.asarray([-1.46385011, -0.87831007, -0.29277002,  0.29277002,  0.87831007, 1.46385011]),
    np.asarray([-1.46385011, -0.87831007, -0.29277002,  0.29277002,  0.87831007, 1.46385011]),
    data_range=2.9277
))
np.allclose(np.asarray(x__), np.asarray([-1.46385011, -0.87831007, -0.29277002,  0.29277002,  0.87831007, 1.46385011]))

2.9277002188455996
[-1.46385011 -0.87831007 -0.29277002  0.29277002  0.87831007  1.46385011]
[-2.5 -1.5 -0.5  0.5  1.5  2.5]
[-1.46385011 -0.87831007 -0.29277002  0.29277002  0.87831007  1.46385011]
0.5855400437691199
[-1.46385011 -0.87831007 -0.29277002  0.29277002  0.87831007  1.46385011]
332.22443992463
inf


/localscratch/miniforge3/envs/train_lvae/lib/python3.9/site-packages/skimage/metrics/simple_metrics.py:163: RuntimeWarning: divide by zero encountered in scalar divide
  return 10 * np.log10((data_range ** 2) / err)


True

In [17]:
x = torch.tensor([1, 2, 3, 4, 5, 6], dtype=torch.float32)
torch_cast_to_float(x)

/home/federico.carrara/Documents/projects/spectral_careamics/src/careamics/utils/metrics.py:158: UserWarning: Casting tensor  of type torch.float32 to double (`torch.float64`).
  


tensor([1., 2., 3., 4., 5., 6.], dtype=torch.float64)