In [1]:
import numpy as np

In [2]:
from careamics.dataset_dev.data_reader import DataReader
from careamics.dataset_dev.patching import RandomPatchSpecsGenerator

In [3]:
rng = np.random.default_rng()

In [4]:
# define example data
array1 = np.arange(36).reshape(1, 6, 6)
array2 = np.arange(50).reshape(2, 5, 5)
target1 = rng.integers(0, 1, size=array1.shape, endpoint=True)
target2 = rng.integers(0, 1, size=array2.shape, endpoint=True)

In [5]:
print(array1)
print(array2)
print(target1)
print(target2)

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]
  [24 25 26 27 28 29]
  [30 31 32 33 34 35]]]
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]

 [[25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]]
[[[1 1 1 1 0 1]
  [0 0 1 0 1 0]
  [0 1 1 1 0 0]
  [0 1 1 0 0 0]
  [0 1 1 1 0 0]
  [1 0 0 0 0 1]]]
[[[0 0 0 1 0]
  [0 1 0 0 1]
  [1 0 1 1 1]
  [1 1 0 0 0]
  [0 1 1 1 0]]

 [[1 0 0 1 1]
  [1 0 1 1 1]
  [1 1 1 0 1]
  [1 0 0 1 0]
  [0 0 0 0 0]]]


In [6]:
# define example readers
input_data_reader = DataReader.from_arrays([array1, array2], axes="SYX")
target_data_reader = DataReader.from_arrays([target1, target2], axes="SYX")

In [7]:
# generate random patch specification
data_shapes = [
    array_reader.data_shape for array_reader in input_data_reader.array_readers
]
patch_specs_generator = RandomPatchSpecsGenerator(data_shapes)
patch_specs = patch_specs_generator.generate(patch_size=(2, 2), seed=42)
patch_specs

[{'data_idx': 0, 'sample_idx': 0, 'coords': (0, 3), 'extent': (2, 2)},
 {'data_idx': 0, 'sample_idx': 0, 'coords': (3, 2), 'extent': (2, 2)},
 {'data_idx': 0, 'sample_idx': 0, 'coords': (2, 4), 'extent': (2, 2)},
 {'data_idx': 0, 'sample_idx': 0, 'coords': (0, 3), 'extent': (2, 2)},
 {'data_idx': 0, 'sample_idx': 0, 'coords': (1, 0), 'extent': (2, 2)},
 {'data_idx': 0, 'sample_idx': 0, 'coords': (2, 4), 'extent': (2, 2)},
 {'data_idx': 0, 'sample_idx': 0, 'coords': (3, 3), 'extent': (2, 2)},
 {'data_idx': 0, 'sample_idx': 0, 'coords': (3, 3), 'extent': (2, 2)},
 {'data_idx': 0, 'sample_idx': 0, 'coords': (2, 0), 'extent': (2, 2)},
 {'data_idx': 1, 'sample_idx': 0, 'coords': (3, 1), 'extent': (2, 2)},
 {'data_idx': 1, 'sample_idx': 0, 'coords': (2, 1), 'extent': (2, 2)},
 {'data_idx': 1, 'sample_idx': 0, 'coords': (0, 3), 'extent': (2, 2)},
 {'data_idx': 1, 'sample_idx': 0, 'coords': (3, 2), 'extent': (2, 2)},
 {'data_idx': 1, 'sample_idx': 0, 'coords': (1, 3), 'extent': (2, 2)},
 {'dat

In [8]:
# extract a subset of patches
input_data_reader.extract_patches(patch_specs[7:11])

[array([[[21, 22],
         [27, 28]]]),
 array([[[12, 13],
         [18, 19]]]),
 array([[[16, 17],
         [21, 22]]]),
 array([[[11, 12],
         [16, 17]]])]

In [9]:
target_data_reader.extract_patches(patch_specs[7:11])

[array([[[0, 0],
         [1, 0]]]),
 array([[[0, 1],
         [0, 1]]]),
 array([[[1, 0],
         [1, 1]]]),
 array([[[0, 1],
         [1, 0]]])]